### ISSUE TITLE
support for multiple cartoon formats

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#11]
edged (current), oval (jmol/pymol), flat, basic (cylinders for helices)
also thickness and height
nucliec sticks

**Comment by mattragoza** [comment]
Do we still want the option to display alpha helices as simple cylinders?

**Comment by dkoes** [comment]
yes, and a ribbon option

**Comment by mattragoza** [comment]
Do you have an example of what the ribbon style should look like?

**Comment by dkoes** [comment]
Basically don't do anything special for helices and sheets (all loop style).  If we could have both a tubular style and a flat style like that it would be great.

**Comment by mattragoza** [comment]
I've added a ribbon option that forces the width of the strand to follow the thickness property rather than being secondary-structure-dependent. This can be specified in addition to the style property, allowing ribbons in oval (tubular), default (edged), rectangle ("rounded edged"), etc. The thickness of any strand can be set to 0 for a "flat" style. For alpha helix cylinders, I'm currently using $3Dmol.GLDraw.drawCylinder(), which has an option for either rounded caps or no caps at all- is this ok for now or should I modify the function to allow flat caps as well, which appears to be what pymol uses for basic alpha helices?

**Comment by dkoes** [comment]
I think we have enough styles now.
