### ISSUE TITLE
Rendering after changing atom's position

### ISSUE THREAD

**Issue by avirshup** [3dmol/3Dmol.js#138]
I'm working on integrating 3dmol.js into an iPython notebook widget. It's actually going really well - I'm really impressed with the API and the library's stability!

My issue is about the best way to do atom-specific animation. This was my first attempt, which didn't work:
```
myatom = glviewer.selectedAtoms({'index':3})[0];
myatom.x = 5.2;
glviewer.render();
```

This didn't actually change the atom's position. However, if I include a change of style, it does work:
```
myatom = glviewer.selectedAtoms({'index':3})[0];
myatom.x = 5.2;
glviewer.setStyle({},{'stick':{}})
glviewer.render();
```

Is there a better way to accomplish this?

**Comment by dkoes** [comment]
render will not rebuilt the 3D geometries if the styles haven't changed - this is a feature since it avoid unnecessarily calculation.  Try calling `removegl` on the model, e.g.:
 `glviewer.getModel(0).removegl()`
and see if that forces a refresh.  I think it should work fine; if it does I can add a `forceRefresh` method to the viewer class that will automatically recalculate the geometries for all the models.

**Comment by dkoes** [comment]
If you are only animating part of a model, it is probably more efficient to extract that part into its own model and only refresh (`removegl`) that model to avoid rebuilding all the geometries in the scene.

**Comment by dkoes** [comment]
Also, if the motions can be precalculated (e.g., [vibrations](http://3dmol.csb.pitt.edu/tests/check/test36.html)) you should use the new animate features.

**Comment by dkoes** [comment]
Hopefully this is sufficiently resolved.. closing.
