### ISSUE TITLE
Adding IsoSurface renders incorrectly

### ISSUE THREAD

**Issue by matt-chan** [3dmol/3Dmol.js#162]
Hi,

I'm trying to render an isosurface from cube file. I used the example from the homepage and substituted benzene-homo.cube with my own cube file. 

Holes are appearing in the surface from my own cube file as I rotate it. I've attached a few screenshots at different rotations here. The object itself should be smooth surfaced. It also doesn't matter how much I zoom in or out. 

Here is my js code:

```
<script src="http://3Dmol.csb.pitt.edu/build/3Dmol.js"> </script>

<script\>
    var $3Dmol = $3Dmol || {};
    var $ = jQuery || {};
    var initShapes = function(viewer) {
                $.get('{{ cubefile }}', function(data){
		            var voldata = new $3Dmol.VolumeData(data, "cube");
                    viewer.addIsosurface(voldata, {isoval: 0.01, color:
                            "blue", alpha: 0.95, smoothness: 10});
                    viewer.addIsosurface(voldata, {isoval: -0.01, color:
                            "red", alpha: 0.95, smoothness: 10});
                    viewer.setStyle({}, {stick:{}});
                    viewer.zoomTo();
{#                    viewer.zoom(.75);#}
                    viewer.render();
                }, 'text');
            };
</script\>
```

![screenshot from 2016-04-01 16-09-30](https://cloud.githubusercontent.com/assets/1048117/14218850/e1967c34-f824-11e5-89a8-a9d3c42d4302.png)
![screenshot from 2016-04-01 16-09-22](https://cloud.githubusercontent.com/assets/1048117/14218852/e198c822-f824-11e5-8570-ed749ece3728.png)
![screenshot from 2016-04-01 16-09-15](https://cloud.githubusercontent.com/assets/1048117/14218853/e199040e-f824-11e5-8e56-6144bbbb10a9.png)
![screenshot from 2016-04-01 16-09-09](https://cloud.githubusercontent.com/assets/1048117/14218851/e19889e8-f824-11e5-87fa-942ca1e3c438.png)

Thanks for your help!

**Comment by ghutchis** [comment]
The cube isosurface is getting cropped. There are two possibilities:

* The cube file itself doesn't have large enough extents for the isosurface you're using - the file itself is cropped. (This happens very often, which is why we keep the checkpoints around.)
* 3DMol.js is doing the cropping

So before we look to 3DMol.js, can you post the cube or check with another program (e.g., Avogadro) to make sure the file isn't cropped? Changing the isoval can help too, since your orbital could be diffuse - picking a tighter tolerance would eliminate the clipping.

**Comment by matt-chan** [comment]
Thanks for the quick reply!

Here's the file on google drive. It was too big to upload onto github...

https://drive.google.com/file/d/0BywUk4GXwoKNU0RGcHZOdTRfM0k/view?usp=sharing

I just tested in avogadro and it seems to work! I also tried an isoval of 0.02 but to no avail.

**Comment by dkoes** [comment]
This issue was that we weren't computing a bounding sphere for isosurfaces. (I use to assume that just using atoms was sufficient to define the zoomto box).  This meant the slab wasn't being set properly. Note that the slab can be manually adjusted with cntrl-right mouse button, and I've added functions to the viewer to do it programmatically.

I've fixed addIsosurface to create a proper bounding sphere.  However, your example is still slightly clipped on the red lobe. It looks to me like this is legitimately running into the edge of the box (adjusting the isosurface value fixes the problem). Please confirm this is okay.

I'd also note that your cube file can probably be safely downsampled for visualization purposes.

I've pushed all these fixes, but am going to wait to update 3dmol.csb.pitt.edu until I polish off the stick imposter code I'm working on.

**Comment by matt-chan** [comment]
Hi David,

Thanks for the very quick bugfix!

Yes, changing the isovalue is okay. I used 0.02 in avogadro to get a good
result.

Yep, the cubefile can be downsampled. I'll talk to some of my labmates
about it.

Thanks!
Matt

On Sat, 2 Apr 2016 at 15:37 David Koes <notifications@github.com> wrote:

> This issue was that we weren't computing a bounding sphere for
> isosurfaces. (I use to assume that just using atoms was sufficient to
> define the zoomto box). This meant the slab wasn't being set properly. Note
> that the slab can be manually adjusted with cntrl-right mouse button, and
> I've added functions to the viewer to do it programmatically.
>
> I've fixed addIsosurface to create a proper bounding sphere. However, your
> example is still slightly clipped on the red lobe. It looks to me like this
> is legitimately running into the edge of the box (adjusting the isosurface
> value fixes the problem). Please confirm this is okay.
>
> I'd also note that your cube file can probably be safely downsampled for
> visualization purposes.
>
> I've pushed all these fixes, but am going to wait to update
> 3dmol.csb.pitt.edu until I polish off the stick imposter code I'm working
> on.
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/3dmol/3Dmol.js/issues/162#issuecomment-204787992>
>
-- 
Matt

Sent from my phone
