### ISSUE TITLE
document the options paramter to addModel

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#217]
The options supported differ based on the file format, but we don't even mention it now.

**Comment by helblazer811** [comment]
I think we should create a specification for these options because it is used in multiple function.

**Comment by helblazer811** [comment]
We definitely need to define the options for the different parsers somewhere.

**Comment by dkoes** [comment]
http://localhost/3dmol/doc/$3Dmol.html#download  is just one place we reference options without defining them.

**Comment by helblazer811** [comment]
What I have done so far is construct a list of all of the parameters that are used for those functions and i am calling it ModelSpec.

**Comment by helblazer811** [comment]
/**
  * Model specification. Used to specify the options of a GLModel.  Depending on the input file format, not all fields may be defined.
  * @typedef ModelSpec
  * @prop {boolean} duplicateAssemblyAtoms- Set to true if you wish to diplicate assembly atoms otherwise false.
  * @prop {boolean} frames - true if you want to add to a new frame and false otherwise
  * @prop {object} vibrate - object specifying the vibration behavior
  * @prop {number} vibrate.frames - number of frames to be created, default to 10
  * @prop {number} vibrate.amplitude -amplitude of distortion, default to 1 (full)
  * @prop {boolean} multimodel - specifies weather or not multiple models are being defined .supported by xyz,sdf, or mol2
  * @prop {boolean} onemol -specifies weather or not the model is of one molecule . Supported by xyz , sdf , mol2
  * @prop {boolean} keepH - specifies weather or not the porgram should keep H . supported by sdf,mol2
  * @prop parseStyle - cdjson
  * @prop {boolean} doAssembly - mcif
  */

//this is an unfinished attempt, i need to make sure no other things are used

**Comment by dkoes** [comment]
These are properties of the model, but options for the parser.  I would call it ParserOptionsSpec, and not all are implemented on all file types.

**Comment by helblazer811** [comment]
Ok. I should be able to do that, and I will also go back and change the
type of option in all of the functions it appears in. I had noticed that
the navigation bar on the website animates down based on the top of the
page not the bottom of the Nav bar. I created an issue for it.
