### ISSUE TITLE
using within and invert selection does not seem to work

### ISSUE THREAD

**Issue by metma99** [3dmol/3Dmol.js#221]
Hello:
I recently started to try out your 3Dmol library in python 2.7 within jupyter.
Very nice project indeed.
I seem to have hit a roadblock though:

The code below shows me the whole protein in stick and elemental colors.
Only if I comment out the first outside line and use the second the script is doing what I need.

p = py3Dmol.view(query='pdb:1t46',width=600,height=600)
outside = {'invert': True, 'within':{'distance': 5, 'sel':{'resn':'STI'}}}
#outside = {'invert': True, 'resi':[600]}
p.setStyle(outside, {'stick': {'colorscheme': 'greenCarbon'}})
p.show()

Is it possible the within selection does not work or am I doing something wrong?
Your input is appreciated.
Markus

**Comment by dkoes** [comment]
I'm traveling so I can't look into this in detail yet, but does it do the right thing without the invert?

**Comment by metma99** [comment]
Issuing the following command does work as expected:
outside = {'within':{'distance': 5, 'sel':{'resn':'STI'}}}
Thank you very much for your reply and I am looking forward to you to look into this at your convenience.

**Comment by dkoes** [comment]
Okay, so the issue is that the selection is actually working as it is defined.  The within specification "intersects the selection with the set of atoms within a given distance from another selection." So 
    outside = {'invert': True, 'within':{'distance': 5, 'sel':{'resn':'STI'}}}
is taking the intersection of the within selection and {'invert': True'} which is nothing.

I've added support for the invert keyword as a property within the within selection in order implement the behavior you desire (7e3bd86).
    outside = {'within':{'distance': 5, 'invert': True, 'sel':{'resn':'STI'}}}

Alec - please add a test case for this behavior.
