### ISSUE TITLE
How to read multi-molecule SDF

### ISSUE THREAD

**Issue by tdudgeon** [3dmol/3Dmol.js#239]
From what I understand it should be possible to read SD files containing multiple molecules but I can't figure out how to do this. When I do 

`viewer.addModel(data, "sdf");`

it works fine, and just reads the first molecule as expected. 
But if I try:

`var models = viewer.addModels(data, "sdf");`

(note the plural addModels) then I get a strange error:

`3Dmol-min.js:618 Uncaught TypeError: Cannot read property '0' of undefined`

Also, somewhat related, what is the way to handle this when using the viewer in embedded mode. I see no data-\* tags that define if the input contains multiple models and if I again use a SDF then I only get the first structure. 

BTW, a typical use case here is having multiple conformers of a molecule, and wanting to see them superimposed.

**Comment by dkoes** [comment]
The first issue is a bug and the second a feature request.  The are both easily addressed and fixes have been pushed.
ab95e4ef5addbefc7e17f9f4a976437e2dc85d16

You can now specify the options for addModel as part of the div specification:
```
     <div style="height: 400px; width: 400px; position: relative;" 
     class='viewer_3Dmoljs' data-href='test_structs/multiple.sdf' 
     data-backgroundcolor='0xffffff' 
     data-options="multimodel:true;onemol:true"></div>
```
Note that some options don't make sense unless you are wrapping them in API calls (e.g., creating multiple frames - you won't see the other frames unless you call animate - hence the need for onemol).
http://3dmol.csb.pitt.edu/tests/testdiv.html

Alec - we need to make sure we have addModel/addModels/addModelsAs.. tests for every file format we support.  This bug was due to only the pdb parser bothering to set modelData, but addModels assumed it was there.

**Comment by dkoes** [comment]
The bugs are fixed.. I'm leaving this open until the appropriate test cases are created.

**Comment by tdudgeon** [comment]
Multi-molecule SDFs work OK now. Thanks!

**Comment by joanimato** [comment]
Hi @dkoes 

Sorry to resurrect this old issue, but how do I display a specific model from the ones obtained by `var models = viewer.addModels(data, "sdf");` 

Say the sdf file has 5 molecules and I want to display number 4. I'm trying to essentially create a button that goes through all structures in the file.

**Comment by dkoes** [comment]
If you added the models as frames, you step through the frames (setFrame).  If the are individual models, you can style them differently by specifying the model identifier in the selection object.
