### ISSUE TITLE
setSurfaceMaterialStyle 

### ISSUE THREAD

**Issue by DrChrisReynolds** [3dmol/3Dmol.js#240]
setSurfaceMaterialStyle works for changing the opacity of an object but not for changing color.

e.g.
glviewer.addSurface($3Dmol.SurfaceType.SES, {color:'0xffff00', opacity: .5 }, {hetflag:false, chain: 'A'}, {hetflag:false, chain: 'A'});

makes a semi-transparent yellow surface, but then

glviewer.setSurfaceMaterialStyle(mysurf,{color: '0x00ff00',opacity: .8 }); 
glviewer.render();

will change the opacity but will not alter the color.

**Comment by dkoes** [comment]
This is doable for solid colors, but we do not retain the mapping between surface patches and atoms so if you want to be able to apply a color mapping to the surface you have to regenerate it.

Is supporting solid color changes sufficient?

**Comment by DrChrisReynolds** [comment]
I was hoping to be able to remap a color function, but if I have to regenerate the surface then I can work with that.
Supporting solid color changes would be useful.

**Comment by dkoes** [comment]
This is implemented now.  Surfaces can be recolored with solid colors or based on volumetric data.  Unfortunately, can't color by atom properties since we've lost the associated atoms at this point (if there's a strong desire, could probably make this work at the cost of additional memory usage).
See (this takes a long time to load due to the large amount of volumetric data):
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test87

Examples:
```
viewer.setSurfaceMaterialStyle(sa, {color: 0x00ff00, opacity: 0.5});
 viewer.setSurfaceMaterialStyle(sb, {opacity:1.0, voldata: data, volscheme: new $3Dmol.Gradient.RWB(-10,10)});
```
