### ISSUE TITLE
PDB animations?

### ISSUE THREAD

**Issue by thomashrabe** [3dmol/3Dmol.js#267]
Looking into 3DMol to replace our JSMol visualization. 
Does 3DMol display animations as we do here?

http://pdbflex.org/cluster.html#!/4hn4A/20981/1a50A

If yes, I would switch immediately.

**Comment by dkoes** [comment]
Sure, if you have multiple frames you can animate like this:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test39
or if you have vibration vectors you can animate like this:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test36
(view source to see the implementation).

**Comment by Jack-XHP** [comment]
Hello, want to ask some additional question about animations. I have a look at the source code and find the multiple frames are from a single downloaded file. Right now I have a list of mol2 files. How can I add them manually as each frame? I try to use addModelsAsFrames call for each file. Yet it only results in overlapping all molecules together into one frame instead of an animation. BTW I use py3Dmol.

```view = py3Dmol.view()
for i in range(10):
    if os.path.isfile('{}.mol2'.format(i)):
        with open('{}.mol2'.format(i), 'r') as content_file:
            mol = content_file.read()
        view.addModelsAsFrames(mol, 'mol2')
view.animate({'loop': 'forward'})
view.setStyle({'stick':{}})
view.setStyle({'model':0},{'stick':{'colorscheme':'cyanCarbon'}})
view.zoomTo()
view.show()```

**Comment by dkoes** [comment]
I would put all your data into a single string and addModelsAsFrames with that.  You'll probably have to pass multimodel:true as an option (can't test it right now - let me know if it works).

**Comment by Jack-XHP** [comment]
Thanks for you help, It works perfectly by simply concat all mol2 file together and  put them in one addModelsAsFrames
