### ISSUE TITLE
Large molecules are clipped when loaded after a small molecule

### ISSUE THREAD

**Issue by justinmc** [3dmol/3Dmol.js#278]
If I load in a small molecule, then load a larger molecule into the same instance of 3dmol, the larger molecule will be clipped and will not fully display.  I discovered that this clipping can be reset by calling `zoomTo`, but I have cases where I don't want to disturb the user's camera.

![clip](https://cloud.githubusercontent.com/assets/389558/23043596/a7d8c1da-f451-11e6-979e-356dbbbc9cff.gif)

**Comment by dkoes** [comment]
That's actually the desired behavior, since zoomTo is suppose to fit the slab to the existing atoms.  center will also reset the slab. I've added a function to the viewer, fitSlab which takes a selection (everything if not specified) and fits the slab to the selection (so everything is visible).

Update your source and try calling it after loading the second model.

**Comment by justinmc** [comment]
Great, `fitSlab` should be exactly what I'm looking for here.  Thank you!

I actually ran into errors when trying to just drop in the latest build into my code to try fitSlab (I've been using the latest 3Dmol npm module release which seems out of date).  If you guys can publish a new version of the npm module including fitSlab whenever that's good to go that would make things easy on me :)

Anyway this issue seems to be solved in master, so I'll go ahead and close the issue.  Thanks for the quick response!

**Comment by dkoes** [comment]
@helblazer811  - close when you've updated npm

**Comment by helblazer811** [comment]
Should be updated.

**Comment by justinmc** [comment]
That worked, thank you guys!
