### ISSUE TITLE
Possible bug with visualization

### ISSUE THREAD

**Issue by alexvakimov** [3dmol/3Dmol.js#386]
I just run into a quite strange behavior of py3Dmol. When trying to visualize a chain of H atoms, I get varying visual outputs depending on the atoms' labels. The code below won't produce any animation/picture. However, it may show something depending on how I call the atoms. E.g. it works fine for all "O" or if I use labels like "H1", "H2", etc. The output may or may not show H atoms depending on what the labels of other atoms are.

```
import py3Dmol
data2 = '''5
Comment
 H     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 H     1.000000    0.000000    0.000000    0.100000    0.100000    0.000000
 H     3.000000    0.000000    0.000000    0.100000    0.200000    0.000000
 H     4.000000    0.000000    0.000000    0.100000    0.000000    0.300000
 H     5.000000    0.000000    0.000000    0.100000    0.000000    0.300000
'''
xyzview = py3Dmol.view(width=800,height=400)
xyzview.addModel(data2,'xyz',{'vibrate': {'frames':10,'amplitude':1}})
xyzview.setBackgroundColor('0xeeeeee')
xyzview.setStyle({'stick':{}})
xyzview.animate({'loop': 'backAndForth'})
xyzview.zoomTo()
xyzview.show()
```

**Comment by dkoes** [comment]
stick will only display bonds.  Since this is an xyx value, the bonds are determined using the distances between atoms.  Since the covalent radius of hydrogen is less than .5, no bonds are identified and there is nothing to render as a stick.  With different atom types you will have different covalent radii which might result in the identification of bonds (e.g. O has a covalent radius of 0.73 so any oxygens less than 1.46 (plus a fudge factor) apart will have a bond).

Render as spheres and you will see the hydrogen atoms.  If you want to have unnatural bond lengths, use a file format, such as sdf, that explicitly specifies the bonds.
