### ISSUE TITLE
[BUG] Cannot load structure for some PDB queries

### ISSUE THREAD

**Issue by onursumer** [3dmol/3Dmol.js#415]
**Describe the bug**
Cannot load structure for some PDB queries.

**To Reproduce**
1. Go to http://3dmol.csb.pitt.edu/viewer.html?pdb=5XZC

**Expected behavior**
Expected to see a structure similar to this one: https://www.rcsb.org/3d-view/5XZC/1

**Comment by dkoes** [comment]
This PDB only contains alpha carbons and so many styles (stick, line, cartoon) will display nothing (there are no bonds).  Spheres or ribbon traces will work.
http://3dmol.csb.pitt.edu/viewer.html?pdb=5XZC&select=all&style=cartoon:style~trace
http://3dmol.csb.pitt.edu/viewer.html?pdb=5XZC&select=all&style=sphere

This is the expected behavior.
