### ISSUE TITLE
cartoon trace clickable ?

### ISSUE THREAD

**Issue by lukaszgit** [3dmol/3Dmol.js#432]
Hello ! Is there a method to make cartoon-trace model clickable ? It somehow works for me for all cartoon styles but not for trace, thanks a lot, Lukasz

**Comment by dkoes** [comment]
Sorry for the delay - end of semester is more than a little busy.

The reason these aren't available is there isn't a clear mapping to atoms since the trace is a bunch of straight sticks.  I could do alpha carbons only fairly easy, would that be sufficient?

Alternatively, you can use the "clicksphere" style to make all atoms clickable independent of their style.

**Comment by lukaszgit** [comment]
Thanks ! I think clickable C-alphas (trace's kinks) would be absolutely sufficient.
(I figured out that in current version one can add C-alpha 'spheres' to the trace 
and then they are clickable but it changes the appearance of the trace a bit and it is
not a very elegant solution).

**Comment by dkoes** [comment]
Instead of adding the alpha carbons as the "sphere" style, add them as the "clicksphere" style and you'll get the desired behavior.

I'll work on putting alpha carbon clickables for the trace style in the next release.

**Comment by lukaszgit** [comment]
Thanks. It worked like a charm !
