### ISSUE TITLE
Scale to fit

### ISSUE THREAD

**Issue by amarcus** [3dmol/3Dmol.js#448]
Hello,

I'm using 3dmol for educational purposes and show models of various compounds, from water to some simple organic molecules, let's say Pyrene C16H10. The problem is lack of adaptive zoom.

Molecule of water takes very little space but more complex molecules take more space, having atoms of the same size. In result, depending on zoom level I set, I either have very small water molecule or too big pyrene molecule. See the attachment.

I wonder, if there's any method to scale molecule to fit the canvas box? Or at least get the size of the model and calculate proper zoom manually?

![zoom-issue](https://user-images.githubusercontent.com/1550259/75154906-e2dda280-571f-11ea-8a4e-021d7df1a03d.jpg)

**Comment by dkoes** [comment]
This is somewhat intentional.  zoomTo is adaptive zoom, but it will not zoom tighter than 5A.  This is because the zoomto calculations are agnostic of the current display style and we want to leave enough room to visualize spheres so we heuristically allow a 2.5A border on each side, which covers most vdw radii.  

I've pushed a fix to make the minimumZoomToDistance a configuration option of the viewer.  
964ded696363f1fe5ed729a5f273a67406800333

Here's an example:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testwaterzoom


The more robust fix is to make zoomTo aware of the current visual radii given the current style
#449
