### ISSUE TITLE
[BUG] Changing the vibration amplitude causes distortion in the structure

### ISSUE THREAD

**Issue by RaphaelRobidas** [3dmol/3Dmol.js#500]
**Describe the bug**
Calling `animate` multiple times eventually distorts a vibrating structure. This is problematic as the `animate` function seems to be the only way to change the amplitude of the vibration animation. When the amplitude is updated, the starting position of the new animation changes from the true position in the .xyz. Depending on the timing of the `animate` calls, this can cause large distortion on the structure.

**To Reproduce**
See the following minimal example:
https://codepen.io/RaphaelRobidas/pen/wvoWmwQ

**Expected behavior**
Changing the amplitude repeatedly should not change the structure.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox
 - Version: 78.6.0esr (64-bit)

**Comment by dkoes** [comment]
The code was not setup to be applied multiple times (at least not while animating) as it would rebase the vibration on whatever frame was currently active.  I've pushed a fix:
4c3f64fdf31cb37e59d72e2b4d7422ecef75bedf

If for some reason you need to use an older version, you can work around the issue by setting the frame before calling vibrate (setFrame(10) in this case because bothWays is set).

**Comment by RaphaelRobidas** [comment]
Both the new version and the workaround with setFrame fix this issue. Thank you!
