### ISSUE TITLE
Errors when trying to load a lot of models

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [3dmol/3Dmol.js#538]
[:LABEL:]
I'm not sure if this could be a BUG.

**Description**
I have included a lot (62 actually) of models in my website [here](https://fisiquimicamente.com/recursos-fisica-quimica/apuntes/formulacion-nomenclatura-quimica/organica/) (source [here](https://github.com/rodrigoalcarazdelaosa/fisiquimicamente/blob/main/content/es/apuntes-formulacion/organica/index.md)). I have checked that all models load fine when including them one by one (testing it locally). But once they're all there, the models won't load. As you can see in the console, I'm getting a lot of these errors:

```
TypeError: Argument 1 ('shader') to WebGL2RenderingContext.shaderSource must be an instance of WebGLShader
45sentryWrapped — helpers.ts:111
```

**Relevant Context**
I'm loading the same models in [these slides](https://fisiquimicamente.com/recursos-fisica-quimica/apuntes/formulacion-nomenclatura-quimica/organica/diapositivas/) (source [here](https://github.com/rodrigoalcarazdelaosa/fisiquimicamente/blob/main/content/es/slides/formulacion-nomenclatura-quimica-organica/index.md)) and weirdly I can see some models, but most of them not.

I'm using version 1.7.0 of 3Dmol.js and I'm testing it with both Google Chrome v94 and Safari v15 on macOS 11.6.

Thank you very much in advance,
Rodrigo

**Comment by dkoes** [comment]
The spoiler tag in your page hides the embedded content by setting its size to zero (as opposed to leaving it the right size and setting display: none).  You can't create a zero sized WebGL canvas, so that was causing the initial problem.  With the fix above (d3c8de41e83458d0d96f077dad58c25e4082ba40) your page works nicely in firefox.

However, it still has issues in Chrome.  This is because there is a maximum number of allowed WebGL contexts (in theory it is 16 for both chrome and firefox, but firefox seems happy to display many more than that).   You will see the message "WARNING: Too many active WebGL contexts. Oldest context will be lost." in the console when this happens. So you only end up with the 16 molecular viewers that were created last.  

This is a hard browser limit, however, we can work around it a bit.  I've pushed a change (4e72ea878b1e1351419e4317e4e0c2e42949d30c) that will regenerate a lost canvas on a resize event.  This means when the spoiler tag is expanded the embedded viewer, if it has been lost, will be recreated and you'll be able to see it.  However, if the user expands enough spoiler tags that >16 viewers are on the page at once then the least recently expanded ones will be deactivated (but they can reset them by toggling the spoiler).

A fancier fix is to catch the lost context event and replace the webgl context with a png image.  Then when a user tries to interact with it, regenerate the 3D context.   However, obviously the disabled context wouldn't be spinning.  This is Issue #292

**Comment by rodrigoalcarazdelaosa** [comment]
Thanks a lot David! That was quick. I guess I can get access to those fixes using the latest version, i.e., loading the script with this line?

```
<script src="https://3Dmol.csb.pitt.edu/build/3Dmol-min.js"></script>
```

I tested it locally but it seems it's not working (I cleared my cache just in case). For now I think I'll be quite happy with those fixes.

Thank you very much again,
Rodrigo

**Comment by dkoes** [comment]
I *just* updated the webserver version.  Try again.

**Comment by dkoes** [comment]
BTW, really beautiful website.

**Comment by rodrigoalcarazdelaosa** [comment]
> BTW, really beautiful website.

So happy you like it. I'm putting a lot of effort to make it look nice and be useful and interesting. The English version is still way behind the Spanish one, but some day all the content will be translated.

**Comment by rodrigoalcarazdelaosa** [comment]
> However, it still has issues in Chrome. This is because there is a maximum number of allowed WebGL contexts (in theory it is 16 for both chrome and firefox, but firefox seems happy to display many more than that). You will see the message "WARNING: Too many active WebGL contexts. Oldest context will be lost." in the console when this happens. So you only end up with the 16 molecular viewers that were created last.

Is the **grid viewer** available when **embedding**? Would it help with this issue?

**Comment by rodrigoalcarazdelaosa** [comment]
> BTW, I'm loading all models locally from my repo (downloading the `sdf` files) as requesting them from PubChem (using the `CID`) was giving me errors too (too many requests). Is there a workaround to that issue? Thanks again!

BTW, the possibility of using `data-cid` to load models from PubChem should be documented [here](https://3dmol.csb.pitt.edu/doc/tutorial-embeddable.html). I thought that only `data-pdb` was possible, and was loading them using `data-href`
