### ISSUE TITLE
Exporting an animated view in HTML or gif

### ISSUE THREAD

**Issue by giammi56** [3dmol/3Dmol.js#549]
Dear community,

I'd like to export a view produced with `py3Dmol` in `HTML` of `gif` format to be embedded in a presentation. I haven't found anything around, therefore I ask here if there is a workaround.

Thank you!

**Comment by dkoes** [comment]
You can get a png: 
https://3dmol.org/doc/$3Dmol.GLViewer.html#pngURI

**Comment by giammi56** [comment]
therefore just static outputs?

**Comment by dkoes** [comment]
I've implement viewer.apng(nframes) in py3Dmol.  This will record nframes worth of changes to the viewer and display them as an animated PNG.  Here is an example:
https://nbviewer.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/saveanim.ipynb

This doesn't work in any hosted environment I can find (e.g. colab) because they sandbox each cell so that the apng cell can't access the viewer in the other cell (and you need them to be distinct cells) but it should work in a local jupyter notebook.

You will need 1.8.0 of py3Dmol.
