### ISSUE TITLE
select in UI does not set background image[cosmetic BUG]

### ISSUE THREAD

**Issue by duerrsimon** [3dmol/3Dmol.js#601]
**Describe the bug**
Minor cosmetic fix so that the select box in the ui sets background to none 

**To Reproduce**
Use a CSS Framework that has styles for select box background (e.g Flowbite in thiscase)

**Expected behavior**
The select box sets inline defaults or !important defaults that cannot be overriden.

**Screenshots**
![image](https://user-images.githubusercontent.com/16979577/171880188-8cff36ab-bd48-461d-9e77-7b6fee97dd98.png)

**Comment by dkoes** [comment]
I'm having difficulty understanding this issue.  This is the html of the select element.  Nothing is marked as important and the background-image isn't set.  You should be able to override what is set with `!important`.

```
<select style="width: auto; border: none; margin: 0px; font-family: Arial; padding: 0px; height: 20px; border-radius: 4px; box-sizing: border-box;"><option value="select">select</option><option value="pdb">pdb</option><option value="mmtf">mmtf</option><option value="cid">cid</option></select>
```

**Comment by duerrsimon** [comment]
The lack of default styles is the problem. The rest of the UI elements of 3Dmol js  are somewhat styled so one would expect the select element to also not respond to whatever other css rules are defined. 

Some other good defaults to add would be background-color and background-image

`<select style="width: auto; border: none; margin: 0px; font-family: Arial; padding: 0px; height: 20px; border-radius: 4px; box-sizing: border-box;background-color:white;background-image:none"><option value="select">select</option><option value="pdb">pdb</option><option value="mmtf">mmtf</option><option value="cid">cid</option></select>`

**Comment by dkoes** [comment]
Hmm.. I disagree, I think that fact that some styles need to be overridden with !important is kludgy and having css automatically applied to elements is the expected behavior of CSS.  Making it more difficult to style 3dmol controls they way you want it is not the right direction.

Probably the best thing would be to pull all the 3dmol element styling into it's own separate style sheet that can be replaced with a user specified one.  This wouldn't actually result in less work for you though - you'd still have to specify the styles you want for the 3dmol widgets to be distinct from your surrounding styles.  But it would get rid of the !important kludge.
