### ISSUE TITLE
CORS policy error when using download function with NextJS

### ISSUE THREAD

**Issue by phoenixthefirebird** [3dmol/3Dmol.js#630]
**Describe the bug**
Access to XMLHttpRequest at 'https://files.rcsb.org/view/2EJ0.mmtf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**To Reproduce**
1. invoke download function on $3dmol package
2. go to inspect in Chrome and you'll see the error message

**Expected behavior**
download function is supposed to fetch the pdb file from rcsb and display the pdf molecule 

**Additional context**
I believe adding 
`     headers: {
      "accept": "application/json",
      "Access-Control-Allow-Origin":"*"
    },`

to $3Dmol.getbin function's ajax request will solve the issue. I appreciate a quick release of the patch as my capstone project depends on it

**Comment by dkoes** [comment]
This is a **response** header.  The client cannot override the security settings of the server.  The RCSB does not have this header set and there's nothing you can do to change that.  I am confused though because you are trying to access an mmtf from "https://files.rcsb.org/view/" and the base URL should be "https://mmtf.rcsb.org/v1.0/full/".  Can you provide an example of how you are using download? Here is an example of correct usage: https://3dmol.org/tests/auto/generate_test.cgi?test=_3dmol_js_download

**Comment by phoenixthefirebird** [comment]
here it is 
![image](https://user-images.githubusercontent.com/55338489/202875216-19b9ca59-1b9d-4dfb-94d0-00d45e891595.png)
I've followed the format over on the documentation not sure why it's going to "https://files.rcsb.org/view/", please let me know!

**Comment by phoenixthefirebird** [comment]
it's weird, I tried using the example code you gave me and the same error occurred 
`Access to XMLHttpRequest at 'https://files.rcsb.org/view/2NBD.mmtf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by phoenixthefirebird** [comment]
I'm also getting `falling back to pdb format` in the console

**Comment by dkoes** [comment]
can you reproduce the problem with v1.8.0?

**Comment by phoenixthefirebird** [comment]
I get this error when I use v.1.8.0's download and I thought to avoid it with 1.7.0
It would be great if you know what's happening here
![image](https://user-images.githubusercontent.com/55338489/202877363-996231cc-a430-48d3-b698-28a0db8ef3f4.png)

**Comment by dkoes** [comment]
Can you switch to the non-minified version and provide more of the stack trace? Are you sure the issue is in the download and not the addModel call which possibly isn't providing the data in the right format?

**Comment by phoenixthefirebird** [comment]
I'm sure it's not the add Model since if I comment out the download call the error does not appear
Here is the stack trace
`Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at $3Dmol.base64ToArray (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:35:32538)
    at e.mmtf.e.MMTF (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:36:291101)
    at o.parseMolData (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:36:188130)
    at o.addMolData (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:36:176356)
    at u (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:35:33810)
    at Object.eval [as success] (webpack-internal:///./node_modules/3dmol/build/3Dmol-min.js:35:34084)
    at fire (webpack-internal:///./node_modules/jquery/dist/jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (webpack-internal:///./node_modules/jquery/dist/jquery.js:3630:7)
    at done (webpack-internal:///./node_modules/jquery/dist/jquery.js:9822:14)
    at XMLHttpRequest.eval (webpack-internal:///./node_modules/jquery/dist/jquery.js:10083:9)`

**Comment by dkoes** [comment]
We add the ajax binary transport (https://www.npmjs.com/package/jquery-binarytransport) in order to download binary data like mmtf files.  I wonder if your using your own version of jquery is causing the problem.  Make sure jquery is loaded before 3dmol and check to see that the transport is defined after 3dmol.js is loaded.

**Comment by phoenixthefirebird** [comment]
That might be it! To clarify this is how I'm using jquery at the moment 
![image](https://user-images.githubusercontent.com/55338489/202881193-938d38b5-293d-4d48-b789-4a1832686eb2.png)
does that mean I should use the jquery-binarytransport for my first line?

**Comment by phoenixthefirebird** [comment]
I believe jquery is loaded before 3dmol, here is the start of my code 
![image](https://user-images.githubusercontent.com/55338489/202883148-82b17423-a6f5-4c20-b6ca-6eef853411cd.png)

how do I check that the transport is defined?

**Comment by dkoes** [comment]
Have you tried using the the regular 3dmol instead of 3dmol-nojquery?

**Comment by phoenixthefirebird** [comment]
looks like https://github.com/3dmol/3Dmol.js/issues/583 is related

**Comment by dkoes** [comment]
Can you provide a self-contained reduced test case I can reproduce the problem?

**Comment by phoenixthefirebird** [comment]
I really appreciate it! I've created a watered-down version of my code and invited you as collaborate on github. Here is the URL to the repo https://github.com/phoenixthefirebird/next_3dmol

**Comment by dkoes** [comment]
Okay, I think I see the issue.  MMTF isn't defined - it hasn't been set in window namespace.  This is an external js library that 3dmol normally bundles, but since you are loading it as a module it is missing.  You can try loading it and setting window.MMTF as a workaround.  I need to improve how this is bundled and referenced.   There's a second bug, which is in the fallback code for dealing with a failure with MMTF, which fails to set the type to PDB instead of MMTF after downloading the PDB.

**Comment by phoenixthefirebird** [comment]
it does work now with MMTF! It is a little clunky to have to download the whole MMTF js repo haha. Thanks so much for your help I really appreciate it!
