### ISSUE TITLE
[BUG] mac + mousewheel -> always zooms in at max zoom

### ISSUE THREAD

**Issue by arogozhnikov** [3dmol/3Dmol.js#682]
**Describe the bug**

here is how it looks on front page:

https://github.com/3dmol/3Dmol.js/assets/6318811/6f4cbc63-244c-4e80-b925-87ead208c870

mac os + mouse wheel + chromium-based browser. I move mousewheel to zoom out and then make a slight zoom-in - but the image zooms in completely. There is no way to slightly zoom in with mousewheel 

ablations:

- firefox not chrome - no problem observed
- touchpad not mousewheel - no problem observed
- behavior is the same for all plots on the front page

**Comment by dkoes** [comment]
I hooked up a scroll wheel mouse to my macbook and it behaved as expected.

If you look at chrome://flags are any of the options that deal with scrolling/mouse behavior set to something other than the default?

**Comment by arogozhnikov** [comment]
Hi @dkoes 
I did not change any flags, but I checked per your advice:
Chrome-flags  + searched for scroll and mouse - nothing non-default. Changed some parameters that could be related to non-default values - no effect on the bug.
I have 3 independent chromium-based browsers and behavior is identical in all of them.
I've tried connecting mouse via different connector - behavior is still the same. (I have very a simple logitech usb mouse)

As a control, I've tried nglview demo + chromium - and zooming via mouse scrolling works as expected.

**Comment by dkoes** [comment]
I'm using Chrome 114.0.5735.90 and macOS 13.3.1.  I've tried both a generic wireless mouse and a logitech wireless mouse and I see the expected behavior.

Are you sure the problem isn't just that you are scrolling too quickly?  

A single "click" of my logitech wheel produces a wheelDelta of 240 in Chrome but only 48 in Firefox (and interestingly on Linux using the same mouse Chrome produces 15).

It would be helpful if you could bring up the debugger and place a breakpoint in the scroll handling code (search for wheelDelta in 3Dmol.js) and let me know what a single wheel click on your system produces.

**Comment by arogozhnikov** [comment]
<img width="551" alt="Screenshot 2023-05-30 at 2 16 40 PM" src="https://github.com/3dmol/3Dmol.js/assets/6318811/85edbfaf-075a-48c9-80d9-66b9595d1391">

See logs: deltas are the same (though they are big). 
It is scale factor that changes. In this screenshot: 4 zoom-outs, one zoom-in (last one)

**Comment by dkoes** [comment]
And does this change if you change the mouse scroll speed in your system preferences?

<img width="690" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/2342142/6ae31795-0b6b-4aa8-9cef-5003de29574b">

Most likely the fix here is to have a scroll speed limit since there are obviously wildly different default values for a given scroll wheel motion across platforms.

**Comment by arogozhnikov** [comment]
yes, changing scroll speed helps!

Agree that just clipping delta at, say, 100 will solve the original issue
