### ISSUE TITLE
py3Dmol does not display on streamlit app and jupyter notebook

### ISSUE THREAD

**Issue by Jiopro** [3dmol/3Dmol.js#692]
I installed py3dmol=2.0.3. When I used it to visualise a PDB file, the code was passed without error, but it left a blank area where it should be displaying the protein structure. 
![image](https://github.com/3dmol/3Dmol.js/assets/26922333/0b12a408-b753-4943-a2cb-bbe5cf41a92e)

**Comment by dkoes** [comment]
Can you provide a reproducible test case? I know nothing about streamlit.  Are there any errors in the console?

**Comment by Jiopro** [comment]
> 

Hi dkoes,
Thanks for replying!
I actually resolved this myself. I manually installed jupyterlab_3dmol extension to jupyter lab, which was explained in [https://pypi.org/project/py3Dmol/](url)< However, for some reason I had to install nodejs in my newly set up ubuntu using 
/sudo apt-get install -y nodejs before installing the extension. As for streamlit, it was because of firefox's defaut webgl setting, I follow the instruction here [https://support.biodigital.com/hc/en-us/articles/218322977-How-to-turn-on-WebGL-in-my-browser#:~:text=If%20you%20are%20having%20trouble%20running%20WebGL%20in%20Firefox%2C%20please,preference%20is%20set%20to%20true.](url), then it worked.

**Comment by qlx17** [comment]
I encounter the same problem as @Jiopro, that is, jupyter notebook does not display the 3D structure. However, in my case, installing **jupyterlab_3dmol** extension does not solve this problem.

To reproduce this problem, I first create a new conda environment using
`conda create -n py3Dmol_test`

then I install **py3Dmol** package using
`conda install py3dmol`

The following code suggests that I have installed py3dmol=2.0.4
![py3dmol_version](https://github.com/3dmol/3Dmol.js/assets/99795569/3a32b44e-98f6-40ff-be16-8797dd1c42ad)

Then, I copy the test code, which is the same as @Jiopro, but the output is a blank area without the desired 3D structure.
![black_output](https://github.com/3dmol/3Dmol.js/assets/99795569/de508a06-20a7-4e42-bd6b-9daac97adbb8)

Following @Jiopro's solution, I then try to install  **jupyterlab_3dmol** extension using
`jupyter labextension install jupyterlab_3dmol`

The output is
```
$ jupyter labextension install jupyterlab_3dmol
(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 
/home/qlx/anaconda3/envs/py3Dmol_test/lib/python3.12/site-packages/jupyterlab/debuglog.py:56: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/home/qlx/anaconda3/envs/py3Dmol_test/lib/python3.12/site-packages/jupyterlab/debuglog.py:57: UserWarning: ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
  warnings.warn(msg[-1].strip())
/home/qlx/anaconda3/envs/py3Dmol_test/lib/python3.12/site-packages/jupyterlab/debuglog.py:58: UserWarning: See the log file for details: /tmp/jupyterlab-debug-9krz1j_k.log
  warnings.warn(f"See the log file for details: {log_path!s}")
```

It requires me to install **Node.js**, as mentioned by @Jiopro. So I install node.js using
`conda install nodejs`
After that, I type `jupyter labextension install jupyterlab_3dmol` again. This time, the `jupyterlab_3dmol` extension is successfully installed. The command `jupyter labextension list` shows that the extension is enabled.
```
$ jupyter labextension list
JupyterLab v4.0.6
/home/qlx/anaconda3/envs/py3Dmol_test/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-notebook/lab-extension v7.0.4 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /home/qlx/anaconda3/envs/py3Dmol_test/share/jupyter/lab
        jupyterlab_3dmol v0.1.1 enabled OK
```

**But even if the extension has been installed, I still get the blank results. Any suggestions to solve this problem?**

I work on WSL, Ubuntu20.04. And I use jupyter extension of VS code. But opening a jupyter notebook in my browser get the same blank results. The package info is as follows:
```
$ conda list
# packages in environment at /home/qlx/anaconda3/envs/py3Dmol_test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h98912ed_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312hf06ca03_0    conda-forge
charset-normalizer        3.3.0              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0           py312h30efb56_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.2             pyh2140261_0    conda-forge
ipython                   8.16.1             pyh0d859eb_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.1.1              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py312h7900ff3_3    conda-forge
jsonschema                4.19.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.19.1             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.1              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.2           py312h7900ff3_0    conda-forge
jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
jupyter_server            2.7.3              pyhd8ed1ab_1    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libnsl                    2.0.0                hd590300_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.46.0               hd590300_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
markupsafe                2.1.3           py312h98912ed_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.9.2              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nodejs                    20.8.0               hb753e55_0    conda-forge
notebook                  7.0.4              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
openssl                   3.1.3                hd590300_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandoc                    3.1.3                h32600fe_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py312h98912ed_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py3dmol                   2.0.4              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.0          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h98912ed_1    conda-forge
pyzmq                     25.1.1          py312h6282b78_1    conda-forge
qtconsole-base            5.4.4              pyha770c72_0    conda-forge
qtpy                      2.4.0              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.10.3          py312h4b3b743_1    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyh41d4057_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py312h98912ed_1    conda-forge
traitlets                 5.11.2             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.6              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.3              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.9              pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
```

**Comment by dkoes** [comment]
[](url)I don't think the jupyterlabe extension is needed anymore.

I installed through conda like you did (just py3dmol, no extension) and it worked fine both on Ubuntu and WSL (tried both Chrome and Edge).  Your jupyter notebook doesn't look like mine, can you explain more how you are launching a notebook (I simply type `jupyter notebook`).

Is it possible that your network settings are preventing the fetching of the structure? Are there any messages in the browser console?

![Screenshot at 2023-10-05 09-08-05](https://github.com/3dmol/3Dmol.js/assets/2342142/20697ea4-9121-4d32-bd50-5f1e734a3980)

**Comment by qlx17** [comment]
# The reason for my problem
Thanks for your replies @Jiopro @dkoes.  Following your suggestions, I think I have found the cause of my problem, **which is because the test code that I used `p = py3Dmol.view(query='mmtf:lycr') ` does not return the "lycr" structure propetly.** **And that is because I wrongly typed the structure name "1ycr" as "lycr"!!!** **I mistakenly typed the lowercase letter "el" instead of the number "one" !!!**  

**For anybody who may encounter the same problem as me and find this thread in the future, I would suggest testing all the other cases in the [examle notebook](https://nbviewer.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/examples.ipynb) and checking your spelling of the structure!!!**

The debug steps that I have tried are as follows.

# My debug steps
First, according to both of your replies, I think there are four possible reasons for my problem.

1. I used `conda` rather than `pip` to install py3Dmol package.
2. My browser webgl setting has some problems.
3. I used jupyter notebook rather than jupyter lab.
4. Networking problems of my browser that prevent the fetching of the structure.

Since @dkoes used conda and jupyter notebook (without extension) and he got the correct result, I decided to skip reason 1 and 3, and first tried to inspect my browser webgl setting. By the way, the package that @Jiopro mentioned is v0.8.0, which is outdated. `conda install py3dmol` gave me version v2.0.4.

Following the instructions in the [link](https://support.biodigital.com/hc/en-us/articles/218322977-How-to-turn-on-WebGL-in-my-browser#:~:text=If%20you%20are%20having%20trouble%20running%20WebGL%20in%20Firefox%2C%20please,preference%20is%20set%20to%20true) that @Jiopro posted before, I veried that the webgl settings of my browsers, both Edge and Chrome, have been enabled.

Then, I tried to check reason 4. I created a new clean environment using `conda`, and only installed py3dmol without jupyter lab extension. The pictures I posted in my previous comment were from [jupyter extension of VS code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks). This time, I lauched the jupyter notebook by typing `jupyter notebook` in my terminal (the same as @dkoes). 

After opening the notebook in Chrome, I ran the test code again, and it still displays a blank area without the structure. Then, I pressed `F12` to open the browser console. I was surprised to find that there was an error showing that the fetching of the structure failed. Opening the link shown in the console (https://mmtf.rcsb.org/v1.0/full/LYCR) gave me a 404 Not Found error.
![fetch_error](https://github.com/3dmol/3Dmol.js/assets/99795569/0d1b1ffc-c968-4a0e-9317-2909c1fb6146)

Now that it seems the blank area is because the code does not get the returned structure, I switched to test some local files. Copying the following test code in the [examle jupyter notebook](https://nbviewer.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/examples.ipynb), I got the correct ressult.
![local_result](https://github.com/3dmol/3Dmol.js/assets/99795569/9de0c141-5fb0-442e-9f01-9857999286a0)

This result indicates that there is no problem when displaying some local data.

Interestingly, if I change the query structure from "mmtf:lycr" to other structures in the [examle notebook](https://nbviewer.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/examples.ipynb), such as "pdb:5ire" or "mmtf:1dc9", the results are correct. So there is no problem with my browser networking, but just with the structure "mmtf:lycr". What's wrong with it? Through a detailed inspection, I found where the problem is. **I just wrongly typed "1ycr" as "lycr"!!!** **I wrongly typed the lowercase letter "el" instead of the number "one".** I cannot remember why I typed the structure name manually instead of just copy and paste in the first place. I have heard of common mistakes of confusion of "l" and "1", "o" and "0", and I try avoiding using these two lowercase letters in variable names. But my negligence and maybe similar display of "l" and "1" by the default font of jupyter notebook have droped me into this pitfall.

I sincerely appreciate your guidance @Jiopro @dkoes, especially for dkoes pointing me to see the messages in the browser console. I learn a new way of debugging now. 

# Suggestions for the py3Dmol project
Looking back on my debugging process, I have several suggestions for the project. 

1. Since the jupyter labextension is not needed anymore, should we remove the installation instruction in the [README](https://github.com/3dmol/3Dmol.js/blob/master/py3Dmol/README.md) file saying that "in order to use with JupyterLab you must install the JupyterLab extension" ? This statement currently may be a misguidence. In addition, now the recommended way to install jupyter lab extensions is through `pip` or `conda` for a prebuilt extension, see the [documentation](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-extensions).

2. It would be much better if the structure is not returned correctly, the code can print some message such as "The structure can not be returned. Please check structure name or your network". Such message can remind the user the blank area is because the code does not get the structure, not because the package is not installed properly.

3. Maybe consider change the structure name in the first demonstration of the [examle notebook](https://nbviewer.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/examples.ipynb) from "1ycr" to others? I think people tend to refer to the first test case, and if the results get wrong, they are easy to get stucked and do not test the results of other cells (at least for me). So using a less confusing structure name in the first test code snippet can help people avoid such mistakes in case somebody types the structure name manually.
