### ISSUE TITLE
DSN6 map format

### ISSUE THREAD

**Issue by publcif** [3dmol/3Dmol.js#738]
Does 3dmol support this format?

**Comment by dkoes** [comment]
No, I’ve never heard of it. Do you have a link to the spec?

**Comment by publcif** [comment]
Its what the pdb are using instead of ccp4 maps (which 3dmol does render):

https://www.rcsb.org/docs/general-help/x-ray-electron-density-maps

**Comment by ghutchis** [comment]
Looks like the closest thing to a spec is here:
http://www.uoxray.uoregon.edu/tnt/manual/node104.html

**Comment by wojdyr** [comment]
> Its what the pdb are using instead of ccp4 maps (which 3dmol does render):

RCSB added files in this format at some point, I think it was used in the NGL viewer. But more recently they started using a map server that transfers maps in small chunks, in BinaryCIF format.

If you'd like to add DSN6, it's implemented [here in xtal.js][1], and [here][2] in my viewer (forked from xtal.js). But I'm not even sure if it still works, because it's never used. CryoEM uses MRC/CCP4 format, and in crystallography almost all programs can calculate maps on the fly from map coefficients in MTZ file. If a map file is occasionally needed, it's typically also in the CCP4 format.

[1]: https://github.com/natechols/xtal.js/blob/41962ca0fe9d0ad8a65cffe562a5ab4d6be96db6/js/xtal.js#L316
[2]: https://github.com/uglymol/uglymol/blob/d801b993b272ecceb0fa1e4dd41438cd854dc10c/src/elmap.ts#L199

**Comment by wojdyr** [comment]
FTR, RCSB PDB just announced a plan to drop the DSN6 format:
https://lists.wwpdb.org/empathy/thread/PEBDMLMJHJN54HSLU6JKJJJTFPOZXQTB
