### ISSUE TITLE
Use yarn or pnpm as the default package manager

### ISSUE THREAD

**Issue by prajwalkulkarni** [3dmol/3Dmol.js#750]
**Is your feature request related to a problem? Please describe.**
The library is currently using `npm` as the default package manager to manage dependencies, and generate production/development builds with the same being used on the CI pipeline as well. `npm` has major issues when it comes to the time taken to install the dependencies, use of disk space and security (because of how it resolves the dependency tree).

**Describe the solution you'd like**
We can instead adapt to using `yarn` or `pnpm` both for local development and on CI, this would reduce the time taken & the disk space used to install `node_modules` along with improved security. This would result in a better DevX(developer experience).
E.g: The size of `yarn.lock` (~5800lines) is `264KB`, whereas the size of `package-lock.json`(~11400lines) is `344KB`.

**Describe alternatives you've considered(Optional)**
I've personally used `yarn` and can vouch for its improved performance when compared to `npm`.

**Additional context(Optional)**
Of the 2 available options (`yarn` and `pnpm`), comparing the benchmarks, the latter seems to outperform the former in almost every aspect. However, I've not used `pnpm` and cannot assure you if that's true, and, I also believe `pnpm` is relatively new and might not have a wider user community when compared to `yarn`.
**Sidenote**: After the implementation, developers would have to run `yarn install` or `pnpm install` instead of `npm i`/`npm install`.

References: 
[https://www.atatus.com/blog/npm-vs-yarn-vs-pnpm/](https://www.atatus.com/blog/npm-vs-yarn-vs-pnpm/)
[https://hackernoon.com/choosing-the-right-package-manager-npm-yarn-or-pnpm](https://hackernoon.com/choosing-the-right-package-manager-npm-yarn-or-pnpm)

@dkoes I'd love to work on this improvement. But, before I start I would want to know your thoughts on this, and whether we should go ahead with `yarn` or `pnpm`(I'm willing to try out `pnpm` as well).

**Comment by dkoes** [comment]
pnpm already works, right?

**Comment by dkoes** [comment]
I mean if you run `pnpm install` inside of a 3Dmol.js checkout it will install 3Dmol.

**Comment by dkoes** [comment]
I have no desire to change the default package manager.

**Comment by prajwalkulkarni** [comment]
Indeed it does install 3Dmol on running `pnpm install` given that the developer has installed `pnpm`, but my point was mostly around generating the lockfile(which would give the contributors a sense of which package manager to use) and also using `yarn`/`pnpm` on CI would result in improved build times as mentioned above.

Also, if you don't mind, may I know why would you prefer `npm` over other package managers?

**Comment by prajwalkulkarni** [comment]
I've been facing an issue since this morning when I try to install the dependencies using `npm install`(failing on `yarn install` as well). From the error, it looks like, the installation is failing when trying to install the `canvas` package that further requires some dependencies installed, but shouldn't it automatically install instead of throwing an error? I'm currently using node 18.0.0(tried on node 16.16.0 too) and npm version 8.11.0
<img width="1392" alt="Screenshot 2024-01-20 at 4 27 54 PM" src="https://github.com/3dmol/3Dmol.js/assets/22348265/291a794f-a04c-4db0-b440-4fb36fa2bb0b">

Perhaps, I might be doing something incorrectly that I'm not aware of, could you kindly help me with the issue here?
NOTE: I'm running this command on the master branch, without making changes to any of the files.

**Comment by NicolasCARPi** [comment]
@prajwalkulkarni issue is on your end. Just tried this without running into an issue:

~~~bash
cd /tmp
git clone --depth 1 https://github.com/3dmol/3Dmol.js
cd 3Dmol.js
npm i
~~~

Installation is successful.

> I have no desire to change the default package manager.

I tend to agree with: "if it ain't broken, don't fix it."

Using `yarn v4` or `pnpm` has its advantages, and my project switched to yarn v4 recently, but it was a lot of work because you can't rely anymore on `node_modules` folder and extracting files from it is more difficult. So while I'm happy it's done, there need to be a strong reason to do it, and the size of the lockfiles or the time it takes to install are not great arguments. Who cares about the size of the lockfile? I know I don't. Who cares if `npm i` takes 25 seconds when it could take 17 seconds? I don't.

> comparing the benchmarks

You're looking at the wrong problem. What benchmarks are you talking about? There is absolutely no difference for the end user. Using a package manager or another is entirely up to the dev and honestly it doesn't change your life, it's nicer yes, more modern yes, but if the lead dev isn't interested in this change, there really isn't a compelling argument to do so.

**Comment by prajwalkulkarni** [comment]
Yes, although it doesn't make any difference to the end user, my argument was with regards to the developer experience, especially on devices with lower bandwidth internet connections and not so good processing power(please correct me if I'm wrong here). Another reason for this proposal would be the accumulating tech debt. I feel when there's something better available and doesn't take a lot of effort, why would you refrain from using it? (But again, as you mentioned from your recent experience that it did take you a lot of effort, my point wouldn't hold valid here.)

Thanks for getting back on this and sharing your thoughts. :) 

And, regarding the installation issue that I mentioned earlier, I'm facing the issue on my macbook (m1, sonoma). It is installing correctly on my windows machine. I might want to look at what's causing the issue on mac.

**Comment by NicolasCARPi** [comment]
Don't get me wrong, I globally agree with you, but I also understand the position of @dkoes and this is typically something that looks nice and easy at first, but then you get deeper and you end up having to write [this yarn plugin](https://github.com/elabftw/elabftw/blob/master/src/tools/yarn-plugin-tinymce.js) when previously all you had to do was run a `cp` command. Please note also that writing this plugin required two devs and reading the actual source code of yarn because this is far from being properly documented.

My example might not apply here, but it's just to say that a change like that might not be without consequences.

> I might want to look at what's causing the issue on mac.

Oh I see, whenever you see `gyp` in node context, it means it's compiled code and won't work on your ARM architecture. I'm sure you'll find a fix for this.

**Comment by dkoes** [comment]
When either yarn or pnpm become more popular than npm, we will switch.  There is tremendous value in using the most popular tools.  Since pnpm is a valid alternative, if performance matters to a developer, they can just use that.

**Comment by prajwalkulkarni** [comment]
> Don't get me wrong, I globally agree with you, but I also understand the position of @dkoes and this 

Yes, I completely get the point you are trying to make, and having the complete context, even I agree with you and David.

> Oh I see, whenever you see gyp in node context, it means it's compiled code and won't work on your ARM architecture. 

Ah, thanks for the heads up, this will help me debug the issue effectively.

Marking the issue as closed.
